#!/bin/bash
# Build script for individual chapter
# Usage: ./build.sh

set -e

CHAPTER_FILE=$(ls chapter*.tex appendix*.tex 2>/dev/null | grep -v standalone | head -1)

if [ -z "$CHAPTER_FILE" ]; then
    echo "Error: No chapter/appendix .tex file found"
    exit 1
fi

CHAPTER_NAME=$(basename "$CHAPTER_FILE" .tex)

echo "=========================================="
echo "Building: $CHAPTER_NAME"
echo "=========================================="

# Extract chapter/appendix number/letter
if [[ "$CHAPTER_NAME" == *"appendix"* ]]; then
    # appendix_a -> 0, appendix_b -> 1...
    LETTER=$(echo "$CHAPTER_NAME" | sed 's/appendix_//' | tr '[:lower:]' '[:upper:]')
    # Convert A to 0, B to 1...
    VAL=$(printf "%d" "'$LETTER")
    COUNTER=$((VAL - 65))
    IS_APPENDIX=true
elif [[ "$CHAPTER_NAME" == *"comparison"* ]]; then
    COUNTER=10
    IS_APPENDIX=false
else
    # chapter02 -> 1
    CHAPTER_NUM=$(echo "$CHAPTER_NAME" | sed 's/[^0-9]//g' | sed 's/^0//')
    if [ -z "$CHAPTER_NUM" ]; then
        COUNTER=0
    else
        COUNTER=$((CHAPTER_NUM - 1))
    fi
    IS_APPENDIX=false
fi

# Create standalone wrapper
cat > standalone.tex << EOF
\documentclass[11pt,a4paper]{book}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{textcomp}
\usepackage{geometry}
\geometry{a4paper, top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm}
\usepackage{graphicx}
\usepackage{float}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{chngcntr} 
\counterwithin{figure}{chapter}
\counterwithin{table}{chapter}
\graphicspath{{./}}
\usepackage{hyperref}
\hypersetup{colorlinks=true, linkcolor=blue, citecolor=blue, urlcolor=blue}
\usepackage{caption}
\captionsetup{font=small, labelfont=bf, format=hang}
\usepackage{titlesec}
\titleformat{\chapter}[display]
  {\normalfont\huge\bfseries}{\chaptertitlename\ \thechapter}{20pt}{\Huge}
\titlespacing*{\chapter}{0pt}{50pt}{40pt}

\newcommand{\figheight}{0.35\textheight}
\newcommand{\imgcopyright}[1]{\textit{\footnotesize #1}}
\newcommand{\authorcreated}{\imgcopyright{Generated by author using Sora2}}
\newcommand{\authorillustration}{\imgcopyright{Illustration by author}}

\newenvironment{chapterabstract}{%
    \small
    \begin{center}\bfseries Abstract\end{center}
    \begin{quotation}
}{%
    \end{quotation}
    \vspace{1em}
}

\usepackage{tcolorbox}
\tcbuselibrary{skins,breakable}
\newtcolorbox{Prompt}{
    colback=gray!5,
    colframe=gray!50,
    boxrule=0.5pt,
    arc=2pt,
    left=8pt, right=8pt, top=6pt, bottom=6pt,
    fontupper=\ttfamily\small,
    before skip=10pt, after skip=10pt
}
\newtcolorbox{promptbox}[1][]{
    colback=blue!5,
    colframe=blue!50,
    boxrule=0.5pt,
    arc=2pt,
    title={#1},
    fonttitle=\bfseries\small
}
\newtcolorbox{resultbox}[1][]{
    colback=green!5,
    colframe=green!50!black,
    boxrule=0.5pt,
    arc=2pt,
    title={#1},
    fonttitle=\bfseries\small
}
\newtcolorbox{yellowbox}[1][]{
    colback=yellow!10,
    colframe=yellow!60!black,
    boxrule=0.5pt,
    arc=2pt,
    title={#1},
    fonttitle=\bfseries\small
}
\newtcolorbox{orangebox}[1][]{
    colback=orange!10,
    colframe=orange!70!black,
    boxrule=0.5pt,
    arc=2pt,
    title={#1},
    fonttitle=\bfseries\small
}
\newtcolorbox{warnbox}[1][]{
    colback=red!5,
    colframe=red!50!black,
    boxrule=0.5pt,
    arc=2pt,
    title={#1},
    fonttitle=\bfseries\small
}
\newtcolorbox{tipbox}[1][]{
    colback=cyan!5,
    colframe=cyan!50!black,
    boxrule=0.5pt,
    arc=2pt,
    title={#1},
    fonttitle=\bfseries\small
}

\usepackage{booktabs}
\usepackage{enumitem}
\usepackage{microtype}
\usepackage{tikz}

\begin{document}
$( [ "$IS_APPENDIX" = true ] && echo "\appendix" )
\setcounter{chapter}{$COUNTER}
\input{$CHAPTER_FILE}
\end{document}
EOF

# Clean auxiliary files
echo "[1/4] Cleaning auxiliary files..."
rm -f standalone.aux standalone.log standalone.out standalone.toc standalone.idx standalone.ind standalone.ilg

# First pass
echo "[2/4] First LaTeX pass..."
pdflatex -interaction=nonstopmode standalone.tex > /dev/null 2>&1 || true

# Generate index if exists
if [ -f standalone.idx ]; then
    echo "[3/4] Generating index..."
    makeindex standalone.idx > /dev/null 2>&1 || true
else
    echo "[3/4] No index to generate..."
fi

# Second pass
echo "[4/4] Final LaTeX pass..."
pdflatex -interaction=nonstopmode standalone.tex || true

# Rename output
if [ -f standalone.pdf ]; then
    mv standalone.pdf "${CHAPTER_NAME}.pdf"
    echo ""
    echo "=========================================="
    echo "Build successful!"
    echo "Output: ${CHAPTER_NAME}.pdf"
    ls -lh "${CHAPTER_NAME}.pdf"
    echo "=========================================="
else
    echo "Build failed. Check standalone.log for errors."
    exit 1
fi
