#!/bin/bash

# Script to compile the main book and individual chapters/appendices
# Author: Auto-generated
# Date: 2025-11-05

set -e  # Exit on error

echo "=========================================="
echo "Starting compilation of English version"
echo "=========================================="

# Create output directory for individual PDFs
mkdir -p build/individual_pdfs

# Function to compile a LaTeX file
compile_latex() {
    local file=$1
    local output_name=$2
    local dir=$(dirname "$file")
    
    echo ""
    echo "Compiling: $output_name"
    echo "------------------------------------------"
    
    cd "$dir"
    
    # First pass
    pdflatex -interaction=nonstopmode "$(basename $file)" > /dev/null 2>&1 || true
    
    # Run bibtex if .aux file exists
    if [ -f "${output_name}.aux" ]; then
        bibtex "${output_name}" > /dev/null 2>&1 || true
    fi
    
    # Second pass
    pdflatex -interaction=nonstopmode "$(basename $file)" > /dev/null 2>&1 || true
    
    # Third pass for references
    pdflatex -interaction=nonstopmode "$(basename $file)" > /dev/null 2>&1 || true
    
    cd - > /dev/null
    
    if [ -f "$dir/${output_name}.pdf" ]; then
        echo "✓ Successfully compiled: ${output_name}.pdf"
        return 0
    else
        echo "✗ Failed to compile: ${output_name}.pdf"
        return 1
    fi
}

# Step 1: Compile main book
echo ""
echo "=========================================="
echo "Step 1: Compiling main book (main.tex)"
echo "=========================================="

pdflatex -interaction=nonstopmode main.tex
bibtex main || true
makeindex main.idx || true
makeglossaries main || true
pdflatex -interaction=nonstopmode main.tex
pdflatex -interaction=nonstopmode main.tex

if [ -f "main.pdf" ]; then
    echo "✓ Main book compiled successfully: main.pdf"
else
    echo "✗ Failed to compile main book"
    exit 1
fi

# Step 2: Create standalone files for each chapter
echo ""
echo "=========================================="
echo "Step 2: Creating standalone chapter PDFs"
echo "=========================================="

# Array of chapters with chapter numbers
chapters=(
    "chapter01:1:Introduction to Sora2"
    "chapter02:2:Getting Started with Sora2"
    "chapter03:3:Mastering Prompt Engineering"
    "chapter04:4:Visual Storytelling Techniques"
    "chapter05:5:Advanced Creative Techniques"
    "chapter06:6:Technical Deep Dive"
    "chapter07:7:Commercial Applications"
    "chapter08:8:Workflow Integration"
    "chapter09:9:Ethics and Best Practices"
    "chapter10:10:Future Trends and Outlook"
    "chapter-sora2-vs-veo3-comparison:11:Sora 2 vs Veo 3 Comparison"
)

for chapter_info in "${chapters[@]}"; do
    IFS=':' read -r chapter_file chapter_num chapter_title <<< "$chapter_info"

    # Create standalone LaTeX file for this chapter
    cat > "build/${chapter_file}_standalone.tex" << EOF
\\documentclass[11pt,letterpaper]{book}

% Apress style packages
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
\\usepackage{geometry}
\\geometry{letterpaper,margin=1in,top=1.25in,bottom=1.25in}

% Graphics and figures
\\usepackage{graphicx}
\\usepackage{float}
\\usepackage{amssymb}
\\graphicspath{{../images/}}

% Index
\\usepackage{makeidx}
\\makeindex

% Hyperlinks
\\usepackage{hyperref}
\\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    pdftitle={${chapter_title}},
    pdfauthor={Xu Zhiping},
}

% Chapter and section formatting
\\usepackage{titlesec}
\\titleformat{\\chapter}[display]
  {\\normalfont\\huge\\bfseries}{\\chaptertitlename\\ \\thechapter}{20pt}{\\Huge}
\\titlespacing*{\\chapter}{0pt}{0pt}{40pt}

% Custom commands for figure sizing
\\newcommand{\\figheight}{0.5\\textheight}

% Captions
\\usepackage{caption}
\\captionsetup{font=small,labelfont=bf,justification=centering}

% Custom command for image copyright
\\newcommand{\\imgcopyright}[1]{\\textit{\\footnotesize #1}}
\\newcommand{\\authorcreated}{\\imgcopyright{Generated by author using Sora2}}
\\newcommand{\\authorillustration}{\\imgcopyright{Illustration by author}}

% Bibliography
\\usepackage{natbib}
\\bibliographystyle{apalike}

% Glossary
\\usepackage[acronym]{glossaries}
\\makeglossaries

% Load glossary definitions
\\input{../glossary}

\\begin{document}

\\title{Chapter ${chapter_num}\\\\
\\large ${chapter_title}}
\\author{Xu Zhiping\\\\
\\small College of Computer Science and Artificial Intelligence\\\\
\\small Fudan University}
\\date{October 2025}
\\maketitle

\\tableofcontents

\\setcounter{chapter}{$((chapter_num - 1))}
\\input{../chapters/${chapter_file}}

\\bibliography{../references}

\\printindex

\\end{document}
EOF

    # Compile the standalone chapter
    compile_latex "build/${chapter_file}_standalone.tex" "${chapter_file}_standalone"
    
    # Move PDF to individual_pdfs directory
    if [ -f "build/${chapter_file}_standalone.pdf" ]; then
        cp "build/${chapter_file}_standalone.pdf" "build/individual_pdfs/${chapter_file}.pdf"
        echo "  → Saved to: build/individual_pdfs/${chapter_file}.pdf"
    fi
done

# Step 3: Create standalone file for all appendices combined
echo ""
echo "=========================================="
echo "Step 3: Creating combined appendices PDF"
echo "=========================================="

cat > "build/appendices_standalone.tex" << 'EOF'
\documentclass[11pt,letterpaper]{book}

% Apress style packages
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{geometry}
\geometry{letterpaper,margin=1in,top=1.25in,bottom=1.25in}

% Graphics and figures
\usepackage{graphicx}
\usepackage{float}
\usepackage{amssymb}
\graphicspath{{../images/}}

% Index
\usepackage{makeidx}
\makeindex

% Hyperlinks
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    pdftitle={Appendices - Mastering Sora2},
    pdfauthor={Xu Zhiping},
}

% Chapter and section formatting
\usepackage{titlesec}
\titleformat{\chapter}[display]
  {\normalfont\huge\bfseries}{\chaptertitlename\ \thechapter}{20pt}{\Huge}
\titlespacing*{\chapter}{0pt}{0pt}{40pt}

% Custom commands for figure sizing
\newcommand{\figheight}{0.5\textheight}

% Captions
\usepackage{caption}
\captionsetup{font=small,labelfont=bf,justification=centering}

% Custom command for image copyright
\newcommand{\imgcopyright}[1]{\textit{\footnotesize #1}}
\newcommand{\authorcreated}{\imgcopyright{Generated by author using Sora2}}
\newcommand{\authorillustration}{\imgcopyright{Illustration by author}}

% Bibliography
\usepackage{natbib}
\bibliographystyle{apalike}

% Glossary
\usepackage[acronym]{glossaries}
\makeglossaries

% Load glossary definitions
\input{../glossary}

\begin{document}

\title{Appendices\\
\large Mastering Sora2: From Language to Light}
\author{Xu Zhiping}
\date{}
\maketitle

\tableofcontents

\appendix
\input{../appendices/appendix_a}
\input{../appendices/appendix_b}
\input{../appendices/appendix_c}
\input{../appendices/appendix_d}
\input{../appendices/appendix_e}

\bibliography{../references}

\printindex

\end{document}
EOF

# Compile the combined appendices
compile_latex "build/appendices_standalone.tex" "appendices_standalone"

# Move PDF to individual_pdfs directory
if [ -f "build/appendices_standalone.pdf" ]; then
    cp "build/appendices_standalone.pdf" "build/individual_pdfs/appendices_all.pdf"
    echo "  → Saved to: build/individual_pdfs/appendices_all.pdf"
fi

# Step 4: Summary
echo ""
echo "=========================================="
echo "Compilation Summary"
echo "=========================================="
echo ""
echo "Main book PDF:"
echo "  ✓ main.pdf"
echo ""
echo "Individual chapter PDFs (in build/individual_pdfs/):"
for chapter_info in "${chapters[@]}"; do
    IFS=':' read -r chapter_file chapter_title <<< "$chapter_info"
    if [ -f "build/individual_pdfs/${chapter_file}.pdf" ]; then
        echo "  ✓ ${chapter_file}.pdf"
    else
        echo "  ✗ ${chapter_file}.pdf (failed)"
    fi
done
echo ""
echo "Combined appendices PDF:"
if [ -f "build/individual_pdfs/appendices_all.pdf" ]; then
    echo "  ✓ appendices_all.pdf"
else
    echo "  ✗ appendices_all.pdf (failed)"
fi
echo ""
echo "=========================================="
echo "Compilation complete!"
echo "=========================================="

